name: Build & Release Firmware

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: platformio run

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v2
        with:
          files: .pio/build/esp32-s3-devkitc-1/firmware.bin
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
